
About to train for 10 epochs
epoch: 0/9, batch 0/16, loss: 1658.0858329379557
epoch: 0/9, batch 10/16, loss: 342.5624572563171
for epoch 0 , average loss is 1118.3252639956509
About to test
Traceback (most recent call last):
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/demo_bmai.py", line 53, in <module>
    main(args)
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/demo_bmai.py", line 44, in main
    results,mean_training_loss = trainer.train(args.epochs)
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/trainer_bmai_2.py", line 195, in train
    mean_height_rel_error, mean_weight_rel_error, avg_test_loss = self.test(epoch)
  File "/home/lts5-ts/Documents/ahmed/bmai_ahmed/trainer_bmai_2.py", line 273, in test
    mean_height_rel_error,mean_weight_rel_error = calculate_mean_absolute_error_results(y_true,y_predictions)
NameError: name 'y_predictions' is not defined
Average test loss is 282.52448833703994